# Generated by Django 5.1.2 on 2024-10-30 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('webpage', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_smartphone', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=5)),
                ('storage', models.CharField(max_length=5)),
                ('Screen_size', models.CharField(max_length=5)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartphones.manufacturer')),
            ],
        ),
    ]
